export const Data = {
  basariliOlunan: [
    {
      subjectName: "Genel Fizik II",
      subjectCode: "BMF1002",
      akts: 5.0,
      subeler: [
        "A - Doç. Dr. Eren Nokta",
        "B - Doç. Dr. Eren Nokta",
        "C - Doç. Dr. Eren Nokta",
      ],
      aciklama: "Alabilir",
      limit: false,
      state: "success",
    },
    {
      subjectName: "Lineer Cebir",
      subjectCode: "BMF1004",
      akts: 5.0,
      subeler: [
        "A - Doç. Dr. Eren Nokta",
        "B - Doç. Dr. Eren Nokta",
        "C - Doç. Dr. Eren Nokta",
      ],
      aciklama: "Alabilir",
      limit: false,
      state: "success",
    },
    {
      subjectName: "Modern Biyoloji ",
      subjectCode: "BMF1008",
      akts: 4.0,
      subeler: [
        "A - Doç. Dr. Eren Nokta",
        "B - Doç. Dr. Eren Nokta",
        "C - Doç. Dr. Eren Nokta",
      ],
      aciklama: "Alabilir",
      limit: false,
      state: "success",
    },
  ],
  programDisi: [
    {
      subjectName: "Hesaplamalı Geometri",
      subjectCode: "BLM4002",
      akts: 5.0,
      subeler: [
        "A - Doç. Dr. Eren Nokta",
        "B - Doç. Dr. Eren Nokta",
        "C - Doç. Dr. Eren Nokta",
      ],
      aciklama: "Alabilir",
      limit: false,
      state: "success",
    },
    {
      subjectName: "İletişim Teknolojilerinde Gelişmeler",
      subjectCode: "BLM3002",
      akts: 6.0,
      subeler: [
        "A - Doç. Dr. Eren Nokta",
        "B - Doç. Dr. Eren Nokta",
        "C - Doç. Dr. Eren Nokta",
      ],
      aciklama: "Alabilir",
      limit: false,
      state: "success",
    },
    {
      subjectName: "Robot Teknolojileri ",
      subjectCode: "BLM2032",
      akts: 3.0,
      subeler: [
        "A - Doç. Dr. Eren Nokta",
        "B - Doç. Dr. Eren Nokta",
        "C - Doç. Dr. Eren Nokta",
      ],
      aciklama: "Alabilir",
      limit: false,
      state: "success",
    },
  ],
  secmeli: [
    {
      subjectName: "Bilimsel Hesaplama",
      subjectCode: "BLM2020",
      akts: 5.0,
      subeler: [
        "A - Doç. Dr. Erlindi Isaj",
        "B - Doç. Dr. Leonit Shabani",
        "C - Doç. Dr. Eren Nokta",
      ],
      aciklama: "Alabilir",
      limit: 50,
      state: "success",
    },
    {
      subjectName: "Devre Analizi",
      subjectCode: "BLM3020",
      akts: 4.0,
      subeler: [
        "A - Doç. Dr. Erlindi Isaj",
        "B - Doç. Dr. Leonit Shabani",
        "C - Doç. Dr. Eren Nokta",
      ],
      aciklama: "Alabilir",
      limit: 40,
      state: "success",
    },
    {
      subjectName: "Çevik Yazılım Geliştirme ",
      subjectCode: "BLM2330",
      akts: 5.0,
      subeler: [
        "A - Doç. Dr. Erlindi Isaj",
        "B - Doç. Dr. Leonit Shabani",
        "C - Doç. Dr. Eren Nokta",
      ],
      aciklama: "Alabilir",
      limit: 50,
      state: "success",
    },
    {
      subjectName: "Bilgisayar Grafiği ",
      subjectCode: "BLM1000",
      akts: 4.0,
      subeler: [
        "A - Doç. Dr. Erlindi Isaj",
        "B - Doç. Dr. Leonit Shabani",
        "C - Doç. Dr. Eren Nokta",
      ],
      aciklama: "Alabilir",
      limit: false,
      state: "success",
    },
  ],
  ustDonem: [
    {
      subjectName: "Kriptografi",
      subjectCode: "BLM3024",
      akts: 6.0,
      subeler: [
        "A - Doç. Dr. Eren Nokta",
        "B - Doç. Dr. Eren Nokta",
        "C - Doç. Dr. Eren Nokta",
      ],
      aciklama: "Alabilir",
      limit: false,
      state: "success",
    },
    {
      subjectName: "Mobil Programlama",
      subjectCode: "BLM4024",
      akts: 4.0,
      subeler: [
        "A - Doç. Dr. Eren Nokta",
        "B - Doç. Dr. Eren Nokta",
        "C - Doç. Dr. Eren Nokta",
      ],
      aciklama: "Alabilir",
      limit: false,
      state: "success",
    },
  ],
  zorunlu: [
    {
      subjectName: "Programlama Dilleri Kavramları",
      subjectCode: "BLM2002",
      akts: 5.0,
      subeler: [
        "A - Doç. Dr. Eren Nokta",
        "B - Doç. Dr. Eren Nokta",
        "C - Doç. Dr. Eren Nokta",
      ],
      aciklama: "Alabilir",
      limit: false,
      state: "failed",
    },
    {
      subjectName: "İleri Veritabanı Sistemleri",
      subjectCode: "BLM3011",
      akts: 4.0,
      subeler: [
        "A - Doç. Dr. Erlindi Isaj",
        "B - Doç. Dr. Eren Nokta",
        "C - Doç. Dr. Leonit Shabani",
      ],
      aciklama: "Alabilir",
      limit: 50,
      state: "success",
    },
    {
      subjectName: "Veri Haberleşmesi",
      subjectCode: "BLM3004",
      akts: 5.0,
      subeler: [
        "A - Doç. Dr. Baha Yolal",
        "B - Doç. Dr. Eren Nokta",
        "C - Doç. Dr. Leonit Shabani",
      ],
      aciklama: "Alabilir",
      limit: 30,
      state: "failed",
    },
    {
      subjectName: "Mikroişlemciler ve Mikrobilgisayar",
      subjectCode: "BLM3005",
      akts: 3.0,
      subeler: [
        "A - Doç. Dr. Erlindi Isaj",
        "B - Doç. Dr. Erlindi Isaj",
        "C - Doç. Dr. Erlindi Isaj",
      ],
      aciklama: "Alabilir",
      limit: 50,
      state: "failed",
    },
    {
      subjectName: "Nesneye Dayalı Analiz ve Tasarım",
      subjectCode: "BLM3020",
      akts: 6.0,
      subeler: [
        "A - Doç. Dr. Eren Nokta",
        "B - Doç. Dr. Eren Nokta",
        "C - Doç. Dr. Eren Nokta",
      ],
      aciklama: "Alabilir",
      limit: false,
      state: "success",
    },
  ],
};
